# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties

spring:
  datasource:
    host: DB_MYSQL_DESAENV04_TESTPROJDB_TESTPROJDB_ENDPOINT
    db: testprojdb
    username: testprojdb_WPROD
    password: DB_MYSQL_DESAENV04_TESTPROJDB_TESTPROJDB_WPROD
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      sql: debug
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt-secret: ${SECRET_JWT}