# Properties file for local/dev enviroment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties

spring:
  datasource:
    host: ${LOCAL_DB_HOST}:${LOCAL_DB_PORT}
    db: ${LOCAL_DB_SCHEMA}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASS}
    initialization-mode: always

  jpa:
    show-sql: false
    defer-datasource-initialization: true
    hibernate:
#      sql: debug
      ddl-auto: update # create-drop para crear las entidades, una vez creadas y finalizado el mododel cambiar a none
    database-platform: org.hibernate.dialect.MySQL8Dialect


server:
  port: 8082 # no cambiar en prod

jwt-secret: ${SECRET_JWT}