# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties

spring:
  datasource:
    host: ${TEST_DB_HOST}:${TEST_DB_PORT}
    db: ${TEST_DB_SCHEMA}
    username: ${TEST_DB_USER}
    password: ${TEST _DB_PASS}
    initialization-mode: always

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
#      sql: debug
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt-secret: ${SECRET_JWT}